### ISSUE TITLE
DevRPL

### ISSUE THREAD

**Issue by DevRPL** [phpid-jakarta/ajari-koding#56]
### Dev DevRPL
- Creator: DevRPL
- URL: https://www.youtube.com/channel/UCQ01qDl8aHD7663B7j-qO5A
- Description: Sharing belajar laravel Crudbooster, dan tutorial linux
- Topic Tags: laravel, linux
- Business Model: FREE
- Tipe: VIDEO
- Rating: 0 (biarkan nilai 0 ini)

**Comment by mazipan** [comment]
Nama produknya apa? Nama creator-nya siapa?

**Comment by indrijunanda** [comment]
Produk : RuangAdmin - Free Admin Control Panel Themes Based on Bootstrap
4
Creator : Indri Junanda

Pada tanggal Min, 28 Jun 2020 pukul 21.00 Irfan Maulana <
notifications@github.com> menulis:
