### ISSUE TITLE
A TypeError issue in production causing a blank page

### ISSUE THREAD

**Issue by zainfathoni** [phpid-jakarta/ajari-koding#7]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/6315466/85670111-21e22b80-b6f3-11ea-84d9-437b06635baf.png">

**Comment by mazipan** [comment]
Root cause: input data with a wrong template

Solution: 
- Add more validation 
- Fix the data

Fix on commit https://github.com/phpid-jakarta/ajari-koding/commit/4a3037904016ef8c190635d435dcb4ac6282390c
