### ISSUE TITLE
Kelas Rekayasa

### ISSUE THREAD

**Issue by yudhatakarma** [phpid-jakarta/ajari-koding#76]
Silahkan isi beberapa data berikut ya:

```
KELAS REKAYASA

- Creator: Puguh Sulistyo Pambudi
- URL: https://puguhsulistyo.xyz
- Description: video pembelajaran php dasar
- Topic Tags: php, codeigniter, css, html
- Business Model: FREE NO ADS
- Tipe: VIDEO
- Rating: 0 (biarkan nilai 0 ini)
```

*Jangan lupa sempatkan tekan tombol ⭐ di repo ini ya*

**Comment by mazipan** [comment]
Sepertinya ini salah type, saya cek ini modelnya Blog.
Atau saya salah?

**Comment by peterjkambey** [comment]
sudah saya upload kalau ada kesalahan nanti direvisi lagi sama mas irfan
